Преобразует модель в классы
htmlacademy-ecmascript/1708789-cinemaddict-14 pull request #5
Opened 2021-04-28 19:20 UTC by Reustick

2021-05-03 17:02 UTC, ant1quar requested changes
Нужно еще линтер победить. посмотри на ошибки. Там мелочи - количество пробелов и всякое тако

2021-05-03 17:02 UTC, ant1quar commented on src/view/footer.js
> +export default class FooterStatistic extends AbstractView {
В таких классах нужно описывать `constructor` и вызовом `super`

2021-05-03 17:02 UTC, ant1quar commented on src/view/user.js
> +export default class User extends AbstractView {
Юзер у тебя должен быть случайным же - через параметр конструктора нужно передавать юзера из комментария

2021-05-21 00:08 UTC, Reustick commented
done

2021-05-22 10:29 UTC, merged